### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by skizzo** [Borewit/musicbrainz-api#873]
Hi,
first of all, thank you for this lib :) 
I'm trying to add it to my (Typescript-powered) project but get this error when trying to use it:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/s/my-project/node_modules/musicbrainz-api/lib/index.js from /Users/s/my-project/src/modules/MusicBrainzModule.ts not supported.
Instead change the require of index.js in /Users/s/my-project/src/modules/MusicBrainzModule.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/s/my-project/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/s/my-project/src/modules/MusicBrainzModule.ts:37:24)
    at m._compile (/Users/s/my-project/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/s/my-project/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/s/my-project/src/modules/index.ts:20:29)
    at m._compile (/Users/s/my-project/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/s/my-project/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/s/my-project/src/KrateMate.ts:13:19)
    at m._compile (/Users/s/my-project/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/s/my-project/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/s/my-project/src/index.ts:15:21)
    at m._compile (/Users/s/my-project/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/s/my-project/node_modules/ts-node/dist/index.js:859:16) {
  code: 'ERR_REQUIRE_ESM'
}
```

Any ideas? Thanks :)

**Comment by Lombardoc4** [comment]
If you're still having this issue, you need to import the package using an import statement not require

ex: `import { MusicBrainzApi} from 'musicbrainz-api';`

If you need require you have to downgrade to a previous version, not sure which

**Comment by skizzo** [comment]
I did exactly that, which leads to the error described in my initial post.

**Comment by Lombardoc4** [comment]
Do you have `type: module` in your package.json file? Otherwise can you share your package.json and file where you import musicbrainz-api

**Comment by Borewit** [comment]
Some hints how to use pure ESM modules: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

I am closing this issue, as it does not directly belong to this project.

**Comment by skizzo** [comment]
Adding `type: module` to my `package.json` leads to my project not being able to run on node 18. Guess I won't be using MusicBrainz after all.
